# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [204]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [205]:
df=pd.read_csv("data/AviationData.csv", encoding="utf-8", encoding_errors="ignore")

C:\Users\Kagechapk\AppData\Local\Temp\ipykernel_28052\827479373.py:1: DtypeWarning: Columns (6: Latitude, 7: Longitude, 28: Broad.phase.of.flight) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("data/AviationData.csv", encoding="utf-8", encoding_errors="ignore")

In [206]:
# Inspect the missing values
print(df.isna().sum())

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [207]:
#Check the data types
df.dtypes

Event.Id                      str
Investigation.Type            str
Accident.Number               str
Event.Date                    str
Location                      str
Country                       str
Latitude                   object
Longitude                  object
Airport.Code                  str
Airport.Name                  str
Injury.Severity               str
Aircraft.damage               str
Aircraft.Category             str
Registration.Number           str
Make                          str
Model                         str
Amateur.Built                 str
Number.of.Engines         float64
Engine.Type                   str
FAR.Description               str
Schedule                      str
Purpose.of.flight             str
Air.carrier                   str
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition             str
Broad.phase.of.flight         str
Report.Status                 str
Publication.Date              str
dtype: object

In [208]:
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

## Filter columns that will provide relevant information for the analysis the client is interested in.

In [209]:
columns= [
    'Event.Date',
    'Aircraft.Category',
    'Make',
    'Model',
    'Amateur.Built',
    'Aircraft.damage',
    'Injury.Severity',
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Uninjured',
    'Purpose.of.flight',
    'FAR.Description'
]

df[columns].head()

,Event.Date,Aircraft.Category,Make,Model,Amateur.Built,Aircraft.damage,Injury.Severity,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Uninjured,Purpose.of.flight,FAR.Description
0,1948-10-24,NaN,Stinson,108-3,No,Destroyed,Fatal(2),2.0,0.0,0.0,Personal,NaN
1,1962-07-19,NaN,Piper,PA24-180,No,Destroyed,Fatal(4),4.0,0.0,0.0,Personal,NaN
2,1974-08-30,NaN,Cessna,172M,No,Destroyed,Fatal(3),3.0,NaN,NaN,Personal,NaN
3,1977-06-19,NaN,Rockwell,112,No,Destroyed,Fatal(2),2.0,0.0,0.0,Personal,NaN
4,1979-08-02,NaN,Cessna,501,No,Destroyed,Fatal(1),1.0,2.0,0.0,Personal,NaN

## Get an overview of what the data looks like

In [210]:
df[columns].info()

<class 'pandas.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Date              88889 non-null  str
 1   Aircraft.Category       32287 non-null  str
 2   Make                    88826 non-null  str
 3   Model                   88797 non-null  str
 4   Amateur.Built           88787 non-null  str
 5   Aircraft.damage         85695 non-null  str
 6   Injury.Severity         87889 non-null  str
 7   Total.Fatal.Injuries    77488 non-null  float64
 8   Total.Serious.Injuries  76379 non-null  float64
 9   Total.Uninjured         82977 non-null  float64
 10  Purpose.of.flight       82697 non-null  str
 11  FAR.Description         32023 non-null  str
dtypes: float64(3), str(9)
memory usage: 8.1 MB

## Inspect missing values

In [211]:
df[columns].isna().sum()

Event.Date                    0
Aircraft.Category         56602
Make                         63
Model                        92
Amateur.Built               102
Aircraft.damage            3194
Injury.Severity            1000
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Uninjured            5912
Purpose.of.flight          6192
FAR.Description           56866
dtype: int64

## Statistical summary of the selected columns

In [212]:
df[columns].describe()

       Total.Fatal.Injuries  Total.Serious.Injuries  Total.Uninjured
count          77488.000000            76379.000000     82977.000000
mean               0.647855                0.279881         5.325440
std                5.485960                1.544084        27.913634
min                0.000000                0.000000         0.000000
25%                0.000000                0.000000         0.000000
50%                0.000000                0.000000         1.000000
75%                0.000000                0.000000         2.000000
max              349.000000              161.000000       699.000000

## Covert Dates and filter aircrafts from 1983 onwards

In [213]:
df['Event.Date']=pd.to_datetime(df['Event.Date'])

df=df[df['Event.Date'].dt.year>=1983]
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
3600,20001214X42040,Accident,LAX83LA093,1983-01-01,"ARROYO GRANDE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,VMC,Landing,Probable Cause,NaN
3601,20001214X42095,Accident,SEA83LA036,1983-01-01,"NEWPORT, OR",United States,NaN,NaN,ONP,NEWPORT MUNICIPAL,...,Personal,NaN,0.0,0.0,1.0,3.0,VMC,Approach,Probable Cause,NaN
3602,20001214X42067,Accident,MKC83LA056,1983-01-01,"WOODBINE, IA",United States,NaN,NaN,3YR,MUNICIPAL,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Landing,Probable Cause,NaN
3603,20001214X42063,Accident,MKC83LA050,1983-01-01,"MARYVILLE, MO",United States,NaN,NaN,78Y,RANKIN,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,NaN
3604,20001214X42018,Accident,LAX83FUG11,1983-01-01,"UPLAND, CA",United States,NaN,NaN,CCB,CABLE,...,Personal,NaN,0.0,0.0,2.0,0.0,VMC,Approach,Probable Cause,NaN

## The client is interested in Airplanes only. So filter Airplanes only and remove the other aircraft types eg. helicopters.

In [214]:
df=df[df['Aircraft.Category']== 'Airplane']

## The client is interested in professionally built airplanes. So remove amateur -Built Aircraft

In [215]:
df=df[df['Amateur.Built']=='No']

## The client is interested in commercial airplanes. So we retain only commercially relevant aircrafts as per FAR Description

In [216]:
df=df[df['FAR.Description'].isin([
            'Part 121: Air Carrier',
            'Part 129: Foreign',
            'Part 135: Air Taxi & Commuter'
])]

In [217]:
df[columns].head()

,Event.Date,Aircraft.Category,Make,Model,Amateur.Built,Aircraft.damage,Injury.Severity,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Uninjured,Purpose.of.flight,FAR.Description
4149,1983-03-18,Airplane,Lockheed,L-1011,No,Minor,Incident,NaN,NaN,588.0,Unknown,Part 121: Air Carrier
4150,1983-03-18,Airplane,Boeing,747,No,Minor,Incident,NaN,NaN,588.0,NaN,Part 129: Foreign
5957,1983-08-21,Airplane,Douglas,DC-10-10,No,Minor,Incident,NaN,NaN,289.0,Unknown,Part 121: Air Carrier
6669,1983-10-28,Airplane,Short Brothers,SD3-30,No,NaN,Fatal(1),1.0,NaN,29.0,Unknown,Part 135: Air Taxi & Commuter
6760,1983-11-08,Airplane,Boeing,727-200,No,Minor,Incident,NaN,NaN,100.0,Unknown,Part 121: Air Carrier

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

## See the missing values in the selected columns

In [218]:
df[columns].isna().sum()

Event.Date                  0
Aircraft.Category           0
Make                        1
Model                       2
Amateur.Built               0
Aircraft.damage            51
Injury.Severity             0
Total.Fatal.Injuries      224
Total.Serious.Injuries    219
Total.Uninjured            57
Purpose.of.flight         155
FAR.Description             0
dtype: int64

In [219]:
average_missing=(df[columns].isnull().mean()*100).round(1)
average_missing

Event.Date                 0.0
Aircraft.Category          0.0
Make                       0.4
Model                      0.7
Amateur.Built              0.0
Aircraft.damage           18.5
Injury.Severity            0.0
Total.Fatal.Injuries      81.2
Total.Serious.Injuries    79.3
Total.Uninjured           20.7
Purpose.of.flight         56.2
FAR.Description            0.0
dtype: float64

## Based on the assumption that missing injury values indicate that no injuries were reported, replace the missing values in the injury columns with zero

In [220]:
df['Total.Fatal.Injuries']=df['Total.Fatal.Injuries'].fillna(0)
df['Total.Serious.Injuries']=df['Total.Serious.Injuries'].fillna(0)
df['Total.Uninjured']=df['Total.Uninjured'].fillna(0)

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

## Compute the total number of passengers. 
Assume that every occupant falls into exactly one category: fatal, serious, minor, or uninjured.

In [221]:
df['Total.Passengers'] = (
    df['Total.Fatal.Injuries'] +
    df['Total.Serious.Injuries'] +
    df['Total.Minor.Injuries'] +
    df['Total.Uninjured']
)

# Compute the sum of serious and fatal injuries

In [222]:
df['fatal.serious.injuries'] = (
    df['Total.Fatal.Injuries'] +
    df['Total.Serious.Injuries']
)

# Compute the proportion of passengers experiencing severe outcome

In [223]:
df['fatal.seriuos.rate']=np.where(
    df['Total.Passengers']>0,
    df['fatal.serious.injuries']/df["Total.Passengers"], np.nan
)

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

# Replace missing values in the Aircraft.Damage column with zero.
The assumption is that Nan implies that the aircraft did not sustain any damages

In [224]:
df['Aircraft.damage']=df['Aircraft.damage'].fillna(0)

# Create a column for Aircraft damage score

In [225]:
damage_map={
    'Destroyed': 3,
    'Substantial':2,
    'Minor':1,
    0:0

}
df['damage.score']=df['Aircraft.damage'].map(damage_map)

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

## Drop the rows with missing make instead of guessing

In [226]:
df[columns].isna().sum()

Event.Date                  0
Aircraft.Category           0
Make                        1
Model                       2
Amateur.Built               0
Aircraft.damage             0
Injury.Severity             0
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Uninjured             0
Purpose.of.flight         155
FAR.Description             0
dtype: int64

In [227]:
df=df.dropna(subset=['Make'])

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

## Drop the rows with missing model instead of guessing

In [228]:
df[columns].isna().sum()

Event.Date                  0
Aircraft.Category           0
Make                        0
Model                       2
Amateur.Built               0
Aircraft.damage             0
Injury.Severity             0
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Uninjured             0
Purpose.of.flight         155
FAR.Description             0
dtype: int64

In [229]:
df=df.dropna(subset=['Model'])

# Inspect counts for each Make–Model combination

In [230]:
model_counts = (
    df.groupby(['Make', 'Model'])
      .size()
      .reset_index(name='count')
      .sort_values('count', ascending=False)
)

model_counts.head(20)

                  Make     Model  count
113             Cessna      208B      9
159  Mcdonnell Douglas  DC-10-30      6
172  Mcdonnell Douglas     MD-11      6
116             Cessna      310R      4
42              Boeing   737-300      4
64              Boeing       767      4
53              Boeing   747-200      4
125       De Havilland     DHC-2      4
71              Boeing       777      3
74              Boeing   777-222      3
112             Cessna       208      3
19               Beech        99      3
67              Boeing   767-300      3
165  Mcdonnell Douglas   DC-9-82      3
117             Cessna      402C      3
34              Boeing   727-200      3
61              Boeing   757-200      3
62              Boeing   757-225      2
45              Boeing   737-400      2
38              Boeing   737-200      2

# Check whether models are unique across manufacturers 
(If this returns rows, then model labels are not unique to a single manufacturer)

In [231]:
duplicate_models = (
    df.groupby('Model')['Make']
      .nunique()
      .reset_index(name='num_makes')
)

duplicate_models = duplicate_models[duplicate_models['num_makes'] > 1]

duplicate_models.head(20)

           Model  num_makes
93      A320-232          2
125  CL-600-2B19          3
129     DC-10-30          2

# Create a unique aircraft-type identifier
(This combines both make and mode to have a unique aircraft type identifier)

In [232]:
df['Plane_Type'] = (
    df['Make'].str.strip().str.upper() +
    '_' +
    df['Model'].str.strip().str.upper()
)
df['Plane_Type'].head(10)

4149           LOCKHEED_L-1011
4150                BOEING_747
5957          DOUGLAS_DC-10-10
6669     SHORT BROTHERS_SD3-30
6760            BOEING_727-200
7708                  BEECH_99
8591     LOCKHEED_L-1011-385-3
10140       SWEARINGEN_SA226TC
14806          DOUGLAS_DC-9-31
16647      SWEARINGEN_SA-226TC
Name: Plane_Type, dtype: str

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

# 1. Engine Type

In [233]:

df['Engine.Type'].value_counts(dropna=False)

Engine.Type
Turbo Fan        83
Unknown          75
Reciprocating    41
Turbo Prop       34
NaN              28
Turbo Jet        12
Name: count, dtype: int64

# Remove leading/trailing whitespace.

In [234]:
df['Engine.Type'] = (
    df['Engine.Type']
    .str.strip()
    )

# 2. Weather Condition

In [235]:
df['Weather.Condition'].value_counts(dropna=False)

Weather.Condition
VMC    149
UNK     64
IMC     40
NaN     20
Name: count, dtype: int64

# Remove leading/trailing whitespace.

In [236]:
df['Weather.Condition'] = (
    df['Weather.Condition']
    .str.strip()
   )

# 3. Number of Engines

In [237]:
df['Number.of.Engines'].value_counts(dropna=False)

Number.of.Engines
2.0    107
NaN    106
1.0     35
3.0     11
4.0     11
0.0      3
Name: count, dtype: int64

There is need to remove impossible number of engine values like 0.

In [238]:
print(df['Number.of.Engines'].dtype)

float64

# 4. Purpose of flight

Inspect

In [239]:
df['Purpose.of.flight'].value_counts(dropna=False)

Purpose.of.flight
NaN            154
Unknown        117
Business         1
Positioning      1
Name: count, dtype: int64

Remove extra spaces

In [240]:
df['Purpose.of.flight'] = (
    df['Purpose.of.flight']
    .str.strip()
)

# 5. Broad Phase of flight

Inspect

In [241]:
df['Broad.phase.of.flight'].value_counts(dropna=False)

Broad.phase.of.flight
NaN            112
Taxi            33
Landing         30
Takeoff         28
Cruise          17
Standing        15
Approach        13
Climb           12
Descent          7
Maneuvering      5
Go-around        1
Name: count, dtype: int64

Remove extra spaces

In [242]:
df['Broad.phase.of.flight'] = (
    df['Broad.phase.of.flight']
    .str.strip()
)

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [243]:
df.isna().sum()

Event.Id                    0
Investigation.Type          0
Accident.Number             0
Event.Date                  0
Location                    4
Country                     1
Latitude                  167
Longitude                 167
Airport.Code              151
Airport.Name              148
Injury.Severity             0
Aircraft.damage             0
Aircraft.Category           0
Registration.Number        62
Make                        0
Model                       0
Amateur.Built               0
Number.of.Engines         106
Engine.Type                28
FAR.Description             0
Schedule                    1
Purpose.of.flight         154
Air.carrier               167
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Minor.Injuries      226
Total.Uninjured             0
Weather.Condition          20
Broad.phase.of.flight     112
Report.Status               0
Publication.Date           82
Total.Passengers          226
fatal.serious.injuries      0
fatal.seriuos.rate        226
damage.score                0
Plane_Type                  0
dtype: int64

# First, I want to combine my select columns (df[coumns]) with the other columns. Since I had cleaned df[columns] I will only update the rows with corresponding values in the other columns

In [244]:
df_clean = df[columns].copy()

In [245]:
df_clean[['Total.Passengers',
            'fatal.serious.injuries',
            'fatal.seriuos.rate',
            'damage.score',
            'Plane_Type',
            'Engine.Type',
            'Weather.Condition',
            'Number.of.Engines',
            'Broad.phase.of.flight'
            ]] = df.loc[
              df_clean.index,
              ['Total.Passengers',
            'fatal.serious.injuries',
            'fatal.seriuos.rate',
            'damage.score',
            'Plane_Type',
            'Engine.Type',
            'Weather.Condition',
            'Number.of.Engines',
            'Broad.phase.of.flight']
          ]

# Inspect missing values in my combined dataframe

In [246]:
df_clean.isna().sum()

Event.Date                  0
Aircraft.Category           0
Make                        0
Model                       0
Amateur.Built               0
Aircraft.damage             0
Injury.Severity             0
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Uninjured             0
Purpose.of.flight         154
FAR.Description             0
Total.Passengers          226
fatal.serious.injuries      0
fatal.seriuos.rate        226
damage.score                0
Plane_Type                  0
Engine.Type                28
Weather.Condition          20
Number.of.Engines         106
Broad.phase.of.flight     112
dtype: int64

# Recalculate the Total.Passengers and fatal.seriuos.rate columns

In [247]:
df_clean['Total.Passengers']=df_clean['Total.Fatal.Injuries']+df_clean['Total.Serious.Injuries']+df_clean['Total.Uninjured']
df_clean['fatal.seriuos.rate']=df_clean['fatal.serious.injuries']/df_clean['Total.Passengers']

# Inspect data after recalculating above columns

In [248]:
df_clean.isna().sum()

Event.Date                  0
Aircraft.Category           0
Make                        0
Model                       0
Amateur.Built               0
Aircraft.damage             0
Injury.Severity             0
Total.Fatal.Injuries        0
Total.Serious.Injuries      0
Total.Uninjured             0
Purpose.of.flight         154
FAR.Description             0
Total.Passengers            0
fatal.serious.injuries      0
fatal.seriuos.rate         20
damage.score                0
Plane_Type                  0
Engine.Type                28
Weather.Condition          20
Number.of.Engines         106
Broad.phase.of.flight     112
dtype: int64

# Drop missing model, Engine.Types and Weather.Condition

In [249]:
df_clean=df_clean.dropna(subset=['Model','Engine.Type','Weather.Condition'])

# Replace the missing fatal.seriuos.rate with zero. This is based on the assumption that its missing because there were no fatal or serious injuries reported

In [250]:
df_clean['fatal.seriuos.rate']=df_clean['fatal.seriuos.rate'].fillna(0)

# Drop purpose of flight since it has so many missing values

In [251]:
df_clean=df_clean.drop(columns=['Purpose.of.flight','Number.of.Engines','Broad.phase.of.flight'])

In [252]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 240 entries, 4149 to 63889
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Date              240 non-null    datetime64[us]
 1   Aircraft.Category       240 non-null    str
 2   Make                    240 non-null    str
 3   Model                   240 non-null    str
 4   Amateur.Built           240 non-null    str
 5   Aircraft.damage         240 non-null    object
 6   Injury.Severity         240 non-null    str
 7   Total.Fatal.Injuries    240 non-null    float64
 8   Total.Serious.Injuries  240 non-null    float64
 9   Total.Uninjured         240 non-null    float64
 10  FAR.Description         240 non-null    str
 11  Total.Passengers        240 non-null    float64
 12  fatal.serious.injuries  240 non-null    float64
 13  fatal.seriuos.rate      240 non-null    float64
 14  damage.score            240 non-null    int64
 15  Plane_Type              240 non-null    str
 16  Engine.Type             240 non-null    str
 17  Weather.Condition       240 non-null    str
dtypes: datetime64[us](1), float64(6), int64(1), object(1), str(9)
memory usage: 35.6+ KB

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [253]:
df_clean.to_csv('cleaned_aviation_data.csv', index=False)